config/routes.rb
Pitagoras::Application.routes.draw do
  resources :logins, only: [:new, :create]
  resources :leers, only: [:new, :create]
  resources :cargas, only: [:new, :create]
  resources :suscriptors, only: [:new, :create]
  resources :correos, only: [:new, :create]
  resources :vers, only: [:new, :create, :notas]

  resource :leers do
  	get :notas
  end
  get "/paginas/*id", to: 'paginas#show'
  root to: 'logins#new'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Pitagoras', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
     <ul class="left">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_alumno.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Pitagoras', page_path('paginas/gestion_alumno') %></li>
  </ul>
  <div class="top-bar-section">
     <ul class="left">
      <%= render 'layouts/navigation_links_alumno' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li class="has-dropdown not-click"><a href="#"><%=session[:persona].materia%></a>

  <ul class="dropdown"><li class="title back js-generated"><h5><a href="javascript:void(0)">Back</a></h5></li>
    <li><label>Opciones</label></li>
    <li><%= link_to "Enviar Correo", new_correo_path %></li>
    <li><%= link_to "Subir Notas", new_carga_path %></li>
    <li><%= link_to "Ver Notas", notas_leers_path %></li>
  </ul>
</li>

app/views/layouts/_navigation_links_alumno.html.erb
<%# add navigation links to this file %>

<li class="has-dropdown not-click"><a href="#">Opciones</a>
  <ul class="dropdown"><li class="title back js-generated"><h5><a href="javascript:void(0)">Back</a></h5></li>
    <li><%= link_to 'Ver Notas', new_ver_path %></li>
    <li><%= link_to 'Subscribirse', new_suscriptor_path %></li>
  </ul>
</li>
       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pitagoras" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mascotas" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <main role="main">
       <%= yield %>
    </main>
  </body>
</html>